language: python
python:
  - "3.5"
  - "3.6"
  # - "3.7"
  # - "3.8"
  - "pypy3"
branches:
  only:
    - master
install:
  - python -V
  - python setup.py build_ext --inplace
  - pip install nose
script:
  - nosetests -v
notifications:
  email:
    on_success: never
    on_failure: change
