language: python
sudo: false
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy-5.6.0"
  - "pypy3.5-5.8.0"
branches:
  only:
    - master
install:
  - python -V
  - python setup.py build_ext --inplace
  - pip install nose
script:
  - nosetests -v
notifications:
  email:
    on_success: never
    on_failure: change
